import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync,writeFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {HistoryStore} from '../src/history.js';import {asksAboutHistory} from '../src/brain.js';
test('exact chronological history keeps full text beyond context and old cap, anchors and times are owner-scoped',()=>{
 const dir=mkdtempSync(join(tmpdir(),'chronology-'));try{const history=new HistoryStore(dir,2),key='telegram:-123',owner='6612253937';
 const add=(id:string,text:string,at:number,senderId=owner,role:'user'|'assistant'='user')=>history.add(key,{id,text,at,senderId,role});
 add('20','second original spelling',20);add('10','first original spelling',10);add('12','someone else',12,'7853500388');add('15','assistant intervened',15,owner,'assistant');
 assert.equal(history.lookup(key,owner,{order:'earliest',role:'user',limit:1}).messages[0].text,'first original spelling');assert.equal(history.lookup(key,owner,{afterId:'10',order:'earliest',role:'user',limit:1}).messages[0].id,'20');assert.equal(history.lookup(key,owner,{from:20,to:20,role:'user'}).messages[0].text,'second original spelling');assert.equal(history.lookup(key,owner,{afterId:'missing'}).missingAnchor,true);assert.equal(history.lookup(key,owner,{query:'First original spelling',exact:true}).matched,0);
 const long='untouched text '.repeat(250);add('30',long,30);assert.equal(history.search(key,owner,'untouched')[0].text,long);
 const retained=history.lookup(key,owner,{order:'earliest',limit:20}).messages;writeFileSync(join(dir,'history-archive.json'),JSON.stringify({[key]:[...retained,...Array.from({length:5002},(_,n)=>({id:String(100+n),text:'filler',at:100+n,senderId:owner,role:'user'}))]}));const reloaded=new HistoryStore(dir,2);reloaded.add(key,{id:'7000',text:'after many records',at:7000,senderId:owner,role:'user'});assert.equal(reloaded.lookup(key,owner,{order:'earliest',role:'user',limit:1}).messages[0].id,'10');assert.equal(reloaded.search(key,owner,'untouched')[0].text,long);
 }finally{rmSync(dir,{recursive:true,force:true});}
});
test('archive migration merges recent records without deletion or duplicate records',()=>{const dir=mkdtempSync(join(tmpdir(),'merge-history-'));try{
 const record=(id:string)=>({id,role:'user',text:id,at:Number(id),senderId:'1'});writeFileSync(join(dir,'history-archive.json'),JSON.stringify({'telegram:1':[record('1')]}));writeFileSync(join(dir,'history.json'),JSON.stringify({'telegram:1':[record('1'),record('2')]}));const store=new HistoryStore(dir,40);assert.deepEqual(store.lookup('telegram:1','1',{order:'earliest'}).messages.map(m=>m.id),['1','2']);
 }finally{rmSync(dir,{recursive:true,force:true});}});
test('history question routing recognizes chronological and timestamp recall requests',()=>{for(const text of ['what did I say first','what did I say next','what did I say at 10:45','quote my earlier message','what was our first message here'])assert.equal(asksAboutHistory(text),true);assert.equal(asksAboutHistory('write a Python function'),false);});
