import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync,writeFileSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {HistoryStore} from '../src/history.js';import {asksAboutHistory} from '../src/brain.js';import {collection,namespace} from '../src/mongo.js';
test('exact chronological history keeps full text beyond context and old cap, anchors and times are owner-scoped',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'chronology-'));try{const key='telegram:-123',owner='6612253937';
 const long='untouched text '.repeat(250);
 const retained=[{id:'20',text:'second original spelling',at:20,senderId:owner,role:'user'},{id:'10',text:'first original spelling',at:10,senderId:owner,role:'user'},{id:'12',text:'someone else',at:12,senderId:'7853500388',role:'user'},{id:'15',text:'assistant intervened',at:15,senderId:owner,role:'assistant'},{id:'30',text:long,at:30,senderId:owner,role:'user'}];
 // Migration is once-only. Seed all legacy records before the first ready call.
 writeFileSync(join(dir,'history-archive.json'),JSON.stringify({[key]:[...retained,...Array.from({length:5002},(_,n)=>({id:String(100+n),text:'filler',at:100+n,senderId:owner,role:'user'}))]}));
 const history=new HistoryStore(dir,2);await history.ready();
 assert.equal((await history.lookup(key,owner,{order:'earliest',role:'user',limit:1})).messages[0].text,'first original spelling');assert.equal((await history.lookup(key,owner,{afterId:'10',order:'earliest',role:'user',limit:1})).messages[0].id,'20');assert.equal((await history.lookup(key,owner,{from:20,to:20,role:'user'})).messages[0].text,'second original spelling');assert.equal((await history.lookup(key,owner,{afterId:'missing'})).missingAnchor,true);assert.equal((await history.lookup(key,owner,{query:'First original spelling',exact:true})).matched,0);
 assert.equal((await history.search(key,owner,'untouched'))[0].text,long);
 const reloaded=new HistoryStore(dir,2);await reloaded.add(key,{id:'7000',text:'after many records',at:7000,senderId:owner,role:'user'});assert.equal((await reloaded.lookup(key,owner,{order:'earliest',role:'user',limit:1})).messages[0].id,'10');assert.equal((await reloaded.search(key,owner,'untouched'))[0].text,long);
 assert.equal(await (await collection('history')).countDocuments({ns:namespace(dir),chat:key}),5008);
 }finally{rmSync(dir,{recursive:true,force:true});}
});
test('archive migration merges recent records without deletion or duplicate records',async()=>{const dir=mkdtempSync(join(tmpdir(),'merge-history-'));try{
 const record=(id:string)=>({id,role:'user',text:id,at:Number(id),senderId:'1'});const archived=JSON.stringify({'telegram:1':[record('1')]}),recent=JSON.stringify({'telegram:1':[record('1'),record('2')]});writeFileSync(join(dir,'history-archive.json'),archived);writeFileSync(join(dir,'history.json'),recent);const store=new HistoryStore(dir,40);assert.deepEqual((await store.lookup('telegram:1','1',{order:'earliest'})).messages.map(m=>m.id),['1','2']);
 await new HistoryStore(dir,40).ready();assert.equal(await (await collection('history')).countDocuments({ns:namespace(dir)}),2);assert.equal(readFileSync(join(dir,'history-archive.json'),'utf8'),archived);assert.equal(readFileSync(join(dir,'history.json'),'utf8'),recent);
 }finally{rmSync(dir,{recursive:true,force:true});}});
test('history question routing recognizes chronological and timestamp recall requests',()=>{for(const text of ['what did I say first','what did I say next','what did I say at 10:45','quote my earlier message','what was our first message here'])assert.equal(asksAboutHistory(text),true);assert.equal(asksAboutHistory('write a Python function'),false);assert.equal(asksAboutHistory('Which color is the circle in the image I sent?'),false);assert.equal(asksAboutHistory('Read the exact text on the photo I sent'),false);});
