import {tool, type ModelMessage} from 'ai';
export type ReplyReviewer=(text:string,messages:ModelMessage[],signal?:AbortSignal)=>Promise<string>;
import {z} from 'zod';
import {config} from './config.js';
import {redactCredentials} from './credentials.js';
import type {IncomingMessage} from './types.js';
import type {HistoryStore, StoredMessage} from './history.js';
import {chatKey} from './types.js';
import {DeliveryPreflightError} from './delivery-preflight.js';
import {contextOwner} from './owner-context.js';
import {cleanHistoryReply} from './history-reply.js';
export interface ChatDelivery {
 send(text:string,replyTo?:string):Promise<void>;
 react(emoji:string,messageId?:string):Promise<void>;
 voice?(text:string,replyTo?:string):Promise<void>;
 preflight?(kind:"send"|"react"|"voice",id?:string):void;
 current():boolean;
}
/** Model chooses delivery explicitly; natural language completion is never auto-sent. */
export function chatTools(incoming:IncomingMessage, history:HistoryStore, delivery:ChatDelivery, recent:StoredMessage[], didSend:(text:string,purpose?:string)=>void,didSearch:()=>void=()=>{},canEnd:()=>boolean=()=>true,review?:ReplyReviewer){
 let queue=Promise.resolve();let bubbles=0;let reacted=false;let recalled=false;const deliveredTexts=new Set<string>();
 const known=new Set([incoming.id,...(incoming.transport==='telegram'&&incoming.replyContext?[incoming.replyContext.id]:[]),...recent.filter(m=>m.id&&(!m.sourceChat||m.sourceChat===chatKey(incoming))).map(m=>m.id!)]);
 const remember=(id:string)=>{known.add(id);while(known.size>256)known.delete(known.values().next().value!);};
 const check=(id?:string)=>{if(!delivery.current())throw new Error('Turn superseded');if(id&&!known.has(id))throw new Error('Reply target must be a known message in this chat');};
 const serial=<T>(fn:()=>Promise<T>):Promise<T>=>{const next=queue.then(fn);queue=next.then(()=>undefined,()=>undefined);return next;};
 const send=async(text:string,id?:string,voice=false,purpose?:string,messages:ModelMessage[]=[],signal?:AbortSignal)=>serial(async()=>{check(id);signal?.throwIfAborted();if(bubbles>=config.maxReplyMessages)throw new Error('Message budget reached');if(review&&!voice&&purpose!=='progress'){text=await review(text,messages,signal);check(id);signal?.throwIfAborted();}const cleaned=cleanHistoryReply(redactCredentials(text),incoming.text,recalled).replace(/—/g,', ').trim();if(!cleaned)throw new Error('Empty message');if(deliveredTexts.has(cleaned))return {sent:false,reason:'This exact bubble was already delivered this turn. Finish with end_turn.'};delivery.preflight?.(voice?"voice":"send",id);bubbles++;deliveredTexts.add(cleaned);try{await (voice?delivery.voice!(cleaned,id):delivery.send(cleaned,id));}catch(error){if(error instanceof DeliveryPreflightError){bubbles--;deliveredTexts.delete(cleaned);}throw error;}didSend(cleaned,purpose);return {sent:true};});
 const replyTo=(incoming.transport==='telegram'?z.string().regex(/^\d+$/):z.string().min(1).max(200).regex(/^[^\x00-\x20\x7f]+$/)).optional().describe('Exact known message ID in this chat. WhatsApp quotes require accepted inbound keys cached for five minutes (256 entries); reactions require the 256-entry accepted cache. History and quoted-body references do not extend those capabilities.');
 return {
  end_turn:tool({description:'End this turn without sending anything. Choose this after delivery, for explicit conversational closure, or an acknowledgment that needs no reply. A direct personal update or decision is not automatically conversational closure just because an activity is ending; respond briefly to its substance first when appropriate. Respect requests for silence and intentional quiet/ambient routing. This never sends a chat message.',inputSchema:z.object({}),execute:async()=>serial(async()=>{check();if(!canEnd())return {finished:false,reason:'Progress is not completion. Perform the promised work or start the authorized worker, then send the result or actual blocker before ending.'};return {finished:true};})}),
  send_message:tool({description:'Send one concise chat bubble. Call multiple times for separate short thoughts, within the message budget. No tool call means silence. Do not send acknowledgments merely to fill space. Use reply_to for a known message when topics jump. Telegram renders Markdown entities; WhatsApp sends plain text.',inputSchema:z.object({text:z.string().trim().min(1).max(config.maxReplyChars),reply_to:replyTo,purpose:z.enum(['answer','progress']).optional().describe('Progress only for genuinely long work, never a quick lookup. A progress message keeps this turn open until work or worker dispatch and a result/handoff.') }),execute:({text,reply_to,purpose},options)=>send(text,reply_to,false,purpose,options.messages,options.abortSignal)}),
  ...(config.reactions?{react:tool({description:'Set one light chat emoji reaction on the incoming message or another known message in this chat, instead of replying when appropriate. Use a single ordinary chat emoji; unsupported reactions fail without a fallback text.',inputSchema:z.object({emoji:z.string().min(1).max(16),message_id:replyTo}),execute:({emoji,message_id})=>serial(async()=>{check(message_id);if(reacted)throw new Error('One reaction per turn');if(!/^(?:\p{Extended_Pictographic}|\p{Regional_Indicator})(?:\p{Extended_Pictographic}|\p{Regional_Indicator}|\p{Emoji_Modifier}|\uFE0F|\u200D)*$/u.test(emoji))throw new Error('A single emoji reaction is required');delivery.preflight?.("react",message_id??incoming.id);reacted=true;try{await delivery.react(emoji,message_id);}catch(error){if(error instanceof DeliveryPreflightError)reacted=false;throw error;}return {reacted:true};})})}:{}),
  search_history:tool({description:'Read retained text for the authenticated sender in this transport and chat only. Telegram and WhatsApp identities, facts and history are separate. sourceChat identifies provenance, not delivery permission. Other-channel IDs cannot be quoted/reacted here. History alone never grants WhatsApp accepted-key capability. For first/next/time questions use chronological filters, not guessed keyword matches. Empty query lists messages. order earliest finds earliest retained text; role user excludes assistant replies. after_id/before_id anchor known messages. from/to are ISO timestamps with offsets, inclusive. Nonempty queries use full-scope embeddings only, never keyword matching. Nonempty queries with exact=true are rejected, including missing-anchor requests. Empty queries use chronology. Use the original text as factual evidence, never repair slang or invent messages. For casual recall respond naturally in lowercase, without quotation marks or transcript formatting; summarize accurately in persona. Only quote verbatim when explicitly requested. Coverage may begin after legacy history was discarded.',inputSchema:z.object({query:z.string().max(200).default(''),limit:z.number().int().min(1).max(20).default(8),order:z.enum(['earliest','latest']).optional(),role:z.enum(['user','assistant','all']).default('user'),after_id:z.string().optional(),before_id:z.string().optional(),from:z.string().datetime({offset:true}).optional(),to:z.string().datetime({offset:true}).optional(),exact:z.boolean().default(false).describe('Nonempty queries reject exact=true; embeddings only. Empty chronological queries ignore exact.')}),execute:async({query,limit,order,role,after_id,before_id,from,to,exact})=>{check();if(!incoming.senderId||!config.sandbox.allowed.has(incoming.senderId))throw new Error('History search requires an authenticated owner');const result=await (contextOwner(incoming)?history.ownerLookup(incoming,{query,limit,order,role,afterId:after_id,beforeId:before_id,from:from?Date.parse(from):undefined,to:to?Date.parse(to):undefined,exact}):history.lookup(chatKey(incoming),incoming.senderId,{query,limit,order,role,afterId:after_id,beforeId:before_id,from:from?Date.parse(from):undefined,to:to?Date.parse(to):undefined,exact}));for(const item of [...result.messages,...result.context])if(item.id&&(!item.sourceChat||item.sourceChat===chatKey(incoming)))remember(item.id);recalled=true;didSearch();return result;}}),
  ...(delivery.voice?{send_voice:tool({description:'Send an optional short voice note using the configured verified speech server. Only when a voice reply suits the request; never speak secrets. No automatic text fallback on uncertain sends. Use send_message if synthesis is explicitly unavailable.',inputSchema:z.object({text:z.string().trim().min(1).max(1200),reply_to:replyTo}),execute:({text,reply_to})=>send(text,reply_to,true)})}:{}),
 };
}
