import { cuaOperationSchema } from './cua-tools.js';
import { createHash, randomBytes, randomUUID } from 'node:crypto';
import { createServer as httpServer, type Server } from 'node:http';
import { WebSocketServer, WebSocket } from 'ws';
import { collection, namespace } from './mongo.js';
import { redactCredentials, registerDesktopCapability } from './credentials.js';

export type LocalAction = 'shell' | 'cua' | 'snapshot';
export interface DeviceRecord { deviceId:string; ownerId:string; tokenHash:string; name:string; platform:string; revoked:boolean; createdAt:number }
export interface PairRecord { codeHash:string; ownerId:string; expiresAt:number }
export interface ActionAudit { ownerId:string; deviceId:string; action:LocalAction; digest:string; state:string; at:number }
export interface LocalDeviceStore {
 putPair(row:PairRecord):Promise<void>; consumePair(codeHash:string,now:number):Promise<PairRecord|null>;
 putDevice(row:DeviceRecord):Promise<void>; byToken(hash:string):Promise<DeviceRecord|null>;
 get(owner:string,id:string):Promise<DeviceRecord|null>; list(owner:string):Promise<DeviceRecord[]>;
 revoke(owner:string,id:string):Promise<boolean>; audit(row:ActionAudit):Promise<void>;
}
export class MongoLocalDeviceStore implements LocalDeviceStore {
 private ns:string;
 constructor(dataDir:string){this.ns=namespace(dataDir);}
 async putPair(row:PairRecord){const pairs=await collection('local_device_pairs');await pairs.createIndex({expiresDate:1},{expireAfterSeconds:0});await pairs.insertOne({...row,ns:this.ns,expiresDate:new Date(row.expiresAt)});}
 async consumePair(codeHash:string,now:number){return await (await collection('local_device_pairs')).findOneAndDelete({ns:this.ns,codeHash,expiresAt:{$gt:now}}) as PairRecord|null;}
 async putDevice(row:DeviceRecord){await (await collection('local_devices')).insertOne({...row,ns:this.ns});}
 async byToken(tokenHash:string){return await (await collection('local_devices')).findOne({ns:this.ns,tokenHash,revoked:false}) as DeviceRecord|null;}
 async get(ownerId:string,deviceId:string){return await (await collection('local_devices')).findOne({ns:this.ns,ownerId,deviceId,revoked:false}) as DeviceRecord|null;}
 async list(ownerId:string){return await (await collection('local_devices')).find({ns:this.ns,ownerId,revoked:false}).toArray() as unknown as DeviceRecord[];}
 async revoke(ownerId:string,deviceId:string){return (await (await collection('local_devices')).updateOne({ns:this.ns,ownerId,deviceId,revoked:false},{$set:{revoked:true}})).modifiedCount===1;}
 async audit(row:ActionAudit){await (await collection('local_device_audit')).insertOne({...row,ns:this.ns});}
}
const hash=(text:string)=>createHash('sha256').update(text).digest('hex');
const secret=()=>randomBytes(32).toString('hex');
export interface ApprovalNotice { approvalId:string;deviceId:string;action:LocalAction;preview:string;digest:string }
export interface LocalDevicesOptions { dataDir:string; authorized:(owner:string)=>boolean;store?:LocalDeviceStore;approvalTtlMs?:number;requestTtlMs?:number }
interface Connection {ws:WebSocket;owner:string;paused:boolean;hello:boolean}
interface Pending {owner:string;deviceId:string;action:LocalAction;args:unknown;digest:string;approvalId:string;approved:boolean;sent:boolean;deadline:number;connection:Connection;resolve:(value:unknown)=>void;reject:(error:Error)=>void;timer:ReturnType<typeof setTimeout>;cleanup:()=>void}
export class LocalDevices {
 private store:LocalDeviceStore; private connections=new Map<string,Connection>();private pending=new Map<string,Pending>();private approvals=new Map<string,string>();
 private notifier?: (owner:string,notice:ApprovalNotice)=>Promise<void>|void;
 private limits=new Map<string,{at:number;n:number}>();private servers=new Set<Server>();private closed=false;
 constructor(private options:LocalDevicesOptions){this.store=options.store??new MongoLocalDeviceStore(options.dataDir);}
 setApprovalNotifier(callback:(owner:string,notice:ApprovalNotice)=>Promise<void>|void){this.notifier=callback;}
 private check(owner:string){if(this.closed||!this.options.authorized(owner))throw new Error('Local device owner unauthorized');}
 private rate(key:string,max:number){const now=Date.now();if(this.limits.size>10000)for(const [k,v] of this.limits)if(now-v.at>60000)this.limits.delete(k);if(this.limits.size>10000)throw new Error('Rate limit');let row=this.limits.get(key);if(!row||now-row.at>60000){row={at:now,n:0};this.limits.set(key,row);}if(++row.n>max)throw new Error('Rate limit');}
 async issuePairCode(owner:string){this.check(owner);this.rate(`pair-owner:${owner}`,5);const code=secret(),expiresAt=Date.now()+120000;registerDesktopCapability(code,expiresAt);await this.store.putPair({codeHash:hash(code),ownerId:owner,expiresAt});return {code,expiresAt};}
 async pair(code:string,name:string,platform:string){if(this.closed||! /^[a-f0-9]{64}$/.test(code)||!name.trim()||name.length>80||!platform.trim()||platform.length>40||/[\x00-\x1f]/.test(name+platform))throw new Error('Invalid pairing');const row=await this.store.consumePair(hash(code),Date.now());if(!row)throw new Error('Pair expired or consumed');this.check(row.ownerId);const deviceId=randomUUID(),token=secret();await this.store.putDevice({deviceId,tokenHash:hash(token),ownerId:row.ownerId,name,platform,createdAt:Date.now(),revoked:false});return {deviceId,token,ownerId:row.ownerId};}
 async list(owner:string){this.check(owner);return (await this.store.list(owner)).map(({deviceId,name,platform,createdAt})=>({deviceId,name,platform,createdAt,connected:!!this.connections.get(deviceId)?.hello,paused:this.connections.get(deviceId)?.paused??true}));}
 async revoke(owner:string,deviceId:string){this.check(owner);const ok=await this.store.revoke(owner,deviceId);if(ok){this.cancelDevice(deviceId,'Device revoked');this.connections.get(deviceId)?.ws.close(1008,'Revoked');this.connections.delete(deviceId);}return ok;}
 private cancelDevice(id:string,message:string){for(const [request,p] of this.pending)if(p.deviceId===id)this.finish(request,new Error(message));}
 private finish(id:string,error?:Error,result?:unknown){const p=this.pending.get(id);if(!p)return;this.pending.delete(id);this.approvals.delete(p.approvalId);clearTimeout(p.timer);p.cleanup();if(error&&p.sent&&p.connection.ws.readyState===WebSocket.OPEN)p.connection.ws.send(JSON.stringify({type:'cancel',id}));void this.store.audit({ownerId:p.owner,deviceId:p.deviceId,action:p.action,digest:p.digest,state:error?'denied':'completed',at:Date.now()}).catch(()=>{});if(error)p.reject(error);else p.resolve(result);}
 async execute(owner:string,deviceId:string,action:LocalAction,args:unknown,signal?:AbortSignal):Promise<unknown>{
 this.check(owner);signal?.throwIfAborted();this.rate(`execute:${owner}`,30);if(!['shell','cua','snapshot'].includes(action))throw new Error('Unsupported local action');const serialized=JSON.stringify(args);if(!serialized||Buffer.byteLength(serialized)>3000)throw new Error('Payload too large');const frozen=JSON.parse(serialized) as unknown;
 if(action==='snapshot'&&(typeof frozen!=='object'||frozen===null||Array.isArray(frozen)||Object.keys(frozen).length))throw new Error('Snapshot accepts no arguments');
 if(action==='cua'&&(typeof frozen!=='object'||frozen===null||Array.isArray(frozen)))throw new Error('Invalid cua arguments');
 if(action==='shell'&&(typeof frozen!=='object'||frozen===null||Array.isArray(frozen)||typeof (frozen as Record<string,unknown>).command!=='string'||Object.keys(frozen).some(k=>k!=='command')))throw new Error('Invalid shell arguments');
 if(action==='cua') {
   const value=frozen as Record<string,unknown>;
   if(!value || typeof value!=='object' || Array.isArray(value) || Object.keys(value).some(k=>k!=='tool'&&k!=='args') || !cuaOperationSchema.safeParse(value.tool).success || !value.args || typeof value.args!=='object' || Array.isArray(value.args)) throw new Error('Invalid local Cua arguments');
 }
 const device=await this.store.get(owner,deviceId);this.check(owner);signal?.throwIfAborted();const conn=this.connections.get(deviceId);if(!device||!conn?.hello||conn.owner!==owner||conn.paused)throw new Error('Device unavailable or paused');if([...this.pending.values()].filter(p=>p.deviceId===deviceId).length>=8)throw new Error('Device busy');
 const id=randomUUID(),approvalId=randomUUID(),digest=hash(JSON.stringify({owner,deviceId,action,args:frozen}));const deadline=Date.now()+Math.min(120000,Math.max(100,this.options.requestTtlMs??60000));
 await this.store.audit({ownerId:owner,deviceId,action,digest,state:'requested',at:Date.now()});this.check(owner);signal?.throwIfAborted();if(this.connections.get(deviceId)!==conn||conn.paused||!await this.store.get(owner,deviceId))throw new Error('Device changed');
 return new Promise((resolve,reject)=>{const abort=()=>this.finish(id,new Error('Request aborted'));const timer=setTimeout(()=>this.finish(id,new Error('Request expired')),Math.min(deadline-Date.now(),action==='snapshot'?120000:Math.min(60000,this.options.approvalTtlMs??60000)));
 const p:Pending={owner,deviceId,action,args:frozen,digest,approvalId,approved:action==='snapshot',sent:false,deadline,connection:conn,resolve,reject,timer,cleanup:()=>signal?.removeEventListener('abort',abort)};this.pending.set(id,p);signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted){abort();return;}if(p.approved){void this.dispatch(id);return;}this.approvals.set(approvalId,id);
 if(!this.notifier){this.finish(id,new Error('Approval unavailable'));return;}Promise.resolve().then(()=>this.notifier!(owner,{approvalId,deviceId,action,preview:redactCredentials(serialized),digest})).catch(()=>this.finish(id,new Error('Approval delivery failed')));
 });}
 async approve(owner:string,approvalId:string,allow:boolean){this.check(owner);const id=this.approvals.get(approvalId),p=id?this.pending.get(id):undefined;if(!id||!p||p.owner!==owner)return false;this.approvals.delete(approvalId);if(!allow){this.finish(id,new Error('Owner denied'));return true;}p.approved=true;await this.dispatch(id);return true;}
 private async dispatch(id:string){const p=this.pending.get(id);if(!p)return;try{this.check(p.owner);if(!p.approved||p.sent||Date.now()>=p.deadline||this.connections.get(p.deviceId)!==p.connection||p.connection.paused||!await this.store.get(p.owner,p.deviceId)||hash(JSON.stringify({owner:p.owner,deviceId:p.deviceId,action:p.action,args:p.args}))!==p.digest)throw new Error('Request no longer authorized');if(this.pending.get(id)!==p)return;this.check(p.owner);if(this.connections.get(p.deviceId)!==p.connection||p.connection.paused||Date.now()>=p.deadline)throw new Error('Request no longer authorized');p.sent=true;p.connection.ws.send(JSON.stringify({type:'request',id,action:p.action,args:p.args,deadline:p.deadline}));}catch{this.finish(id,new Error('Request no longer authorized'));}}
 createServer():Server {const server=httpServer(async(req,res)=>{try{this.rate(`http:${req.socket.remoteAddress??'unknown'}`,20);if(req.method!=='POST'||req.url!=='/local-devices/pair'||req.headers.origin){res.writeHead(404).end();return;}let bytes=0;const chunks:Buffer[]=[];for await(const chunk of req){bytes+=chunk.length;if(bytes>2048)throw new Error('Body too large');chunks.push(chunk);}const body=JSON.parse(Buffer.concat(chunks).toString()) as Record<string,unknown>;if(typeof body.code!=='string'||typeof body.name!=='string'||typeof body.platform!=='string')throw new Error('Bad body');const paired=await this.pair(body.code,body.name,body.platform);res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'}).end(JSON.stringify(paired));}catch{res.writeHead(403).end('Denied');}});
 const wss=new WebSocketServer({noServer:true,maxPayload:8388608,perMessageDeflate:false});const heartbeat=setInterval(()=>{for(const ws of wss.clients){if(!alive.has(ws)){ws.terminate();continue;}alive.delete(ws);ws.ping();}},30000);heartbeat.unref();const alive=new Set<WebSocket>();wss.on('connection',ws=>{alive.add(ws);ws.on('pong',()=>alive.add(ws));ws.on('close',()=>alive.delete(ws));});server.on('upgrade',(req,socket,head)=>{void(async()=>{try{this.rate(`ws:${req.socket.remoteAddress??'unknown'}`,30);if(req.url!=='/local-devices/connect'||req.headers.origin)throw new Error('Denied');const auth=req.headers.authorization;if(!auth||!/^Bearer [a-f0-9]{64}$/.test(auth))throw new Error('Denied');const device=await this.store.byToken(hash(auth.slice(7)));if(!device)throw new Error('Denied');this.check(device.ownerId);wss.handleUpgrade(req,socket,head,ws=>{alive.add(ws);ws.on('pong',()=>alive.add(ws));ws.on('close',()=>alive.delete(ws));this.attach(device,ws);});}catch{socket.write('HTTP/1.1 403 Forbidden\r\nConnection: close\r\n\r\n');socket.destroy();}})();});server.on('close',()=>{clearInterval(heartbeat);alive.clear();wss.close();this.servers.delete(server);});this.servers.add(server);return server;}
 private attach(device:DeviceRecord,ws:WebSocket){this.cancelDevice(device.deviceId,'Device reconnected');this.connections.get(device.deviceId)?.ws.close(1008,'Replaced');const conn:Connection={ws,owner:device.ownerId,paused:true,hello:false};this.connections.set(device.deviceId,conn);const helloTimer=setTimeout(()=>ws.close(1008,'Hello required'),5000);ws.on('close',()=>{clearTimeout(helloTimer);if(this.connections.get(device.deviceId)===conn){this.cancelDevice(device.deviceId,'Disconnected');this.connections.delete(device.deviceId);}});ws.on('error',()=>ws.close());ws.on('message',(data)=>{try{this.check(conn.owner);this.rate(`msg:${device.deviceId}`,120);if(this.connections.get(device.deviceId)!==conn)throw new Error('Replaced');const msg=JSON.parse(data.toString()) as Record<string,unknown>;if(!conn.hello){if(msg.type!=='hello'||msg.version!==1)throw new Error('Hello required');conn.hello=true;clearTimeout(helloTimer);return;}if(msg.type==='pause'&&typeof msg.paused==='boolean'){conn.paused=msg.paused;if(conn.paused)this.cancelDevice(device.deviceId,'Device paused');return;}if(msg.type==='result'&&typeof msg.id==='string'&&typeof msg.ok==='boolean'){const p=this.pending.get(msg.id);if(!p||!p.sent||p.connection!==conn||p.owner!==conn.owner)return;if(Date.now()>=p.deadline){this.finish(msg.id,new Error('Request expired'));return;}this.finish(msg.id,msg.ok?undefined:new Error('Local device action failed'),msg.result);return;}throw new Error('Invalid message');}catch{this.cancelDevice(device.deviceId,'Invalid connector message');ws.close(1008,'Denied');}});}
 async close(){this.closed=true;for(const id of [...this.pending.keys()])this.finish(id,new Error('Local device service closed'));for(const c of this.connections.values())c.ws.close(1001,'Shutdown');this.connections.clear();await Promise.all([...this.servers].map(s=>new Promise<void>(resolve=>{s.close(()=>resolve());s.closeAllConnections();})));this.approvals.clear();}
}
